language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  - sw_ver=$(php -r "echo PHP_VERSION_ID < 70200 ? '-4.5.10': '';") && pecl install --onlyreqdeps --nobuild swoole${sw_ver} && cd "$(pecl config-get temp_dir)/swoole" && phpize && ./configure --enable-openssl && make -j$(nproc) && make -j$(nproc) install && cd -
  - composer install

script: composer test
